### PR TITLE
Ue5 Update, Few changes to things.

### PR DESCRIPTION
**Pull request by lAtom1kl**

### CODE REVIEW

**Comment by lAtom1kl** [comment]
UE5 Update, I know you guys are not updating to UE5, but here is the patch.
Lots of Updates Here.

**Comment by lAtom1kl** [comment]
Sorry Something on github broken. This is MY experiential code for PB movement so far in unreal engine 5. I will be constantly update this code until i get it right.

**Review by mastercoms — CHANGES_REQUESTED** [review]
movement in the character movement component is based on the capsule, not on the mesh. this is how it works in the engine. there should no reason to change these calls to mesh. what exactly are you trying to accomplish? are there any videos of the problems you experienced?

**Comment by lAtom1kl** [comment]
> movement in the character movement component is based on the capsule, not on the mesh. this is how it works in the engine. there should no reason to change these calls to mesh. what exactly are you trying to accomplish? are there any videos of the problems you experienced?

https://www.youtube.com/watch?v=uMY2O_yZbyo&ab_channel=atom1k

Movement was getting stuck understanding acceleration from walk to sprint. I will look into this right now and update the code, If you say its capsule based, then its capsule based. you guys wrote the code.

**Comment by lAtom1kl** [comment]
> movement in the character movement component is based on the capsule, not on the mesh. this is how it works in the engine. there should no reason to change these calls to mesh. what exactly are you trying to accomplish? are there any videos of the problems you experienced?

Updated. Working 100% Crouching is no longer broken, and movement looks smooth. Now I need to do some networking :)

**Pull request closed without merging**
