### PR TITLE
Fixed header inclusion.

### PR DESCRIPTION
**Pull request by tomlister**
Is able to compile on UE 4.24.3

### CODE REVIEW

**Comment by mastercoms** [comment]
Thanks for the contribution!

**Comment by tomlister** [comment]
No worries!

**Comment by IaroslavTernovy** [comment]
@tomlister Hi, I'am pretty new to the unreal engine, Do I need to do someting to use this plugin in my project ? I tried to compile this plugin by using

> .\RunUAT.bat BuildPlugin -targetplatforms=Win32+Win64 

but it giving my an error.  Can you help me please ?

**Comment by donovan1212** [comment]
Throw it in your UE4 project under plugins (you might have to create it
yourself) Then run the project, If it is not compiled for your project,
remove it create a C++ class (or do not if you already have one) and throw
it back into that folder and it will compile.

**Comment by IaroslavTernovy** [comment]
UE giving me an Error when I just trying to copy paste it under folder plugin, 
image
image

**Comment by beauburrows** [comment]
When I got the same error ("Try rebuilding manually"), I had to delete the "Binaries", "Saved" and "Intermediate" folders both in my project and plugins folders, then right click the project file and "generate visual studio project files". Then open the VS solution and build from there to get it working again (not sure why this happens.

Also note that once your project does open successfully with the plugin you can edit the plugin in Visual Studio, then in Unreal go to Window>Developer Tools>Modules and just click "Recompile" next to "PBCharacterMovement" - so you don't have to restart the engine to make changes to the source code.

**Comment by tomlister** [comment]
Make sure you have Visual Studio 2017 installed along with the desktop, c#
and c++ and game development libraries. Make a new c++ project, chuck the
folder under plugins. Open the sln and build the project. Once built chuck
the plugin folder into your main project and add a new c++ class (otherwise
you can't run the packaged version of the game).

**Pull request merged**
